
###
# Test your FastAPI endpoints

POST http://127.0.0.1:8000/add
Content-Type: application/json
Accept: application/json

{
"name": "elon"
}

###
POST http://127.0.0.1:8000/del?id=5
Accept: application/json

###

GET http://127.0.0.1:8000/get?id=4
Accept: application/json

###

GET http://127.0.0.1:8000/
Accept: application/json
